[package]
name = "serde-pod"
version = "0.1.0"
authors = ["Mingun <alexander_sergey@mail.ru>"]

[dependencies]
byteorder = { version = "1.2", features = ["i128"] }
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
quickcheck = "0.7"
